### ISSUE TITLE
Create Location Class

### ISSUE THREAD

**Issue by trangtruongus** [trangtruongus/CPW221-TeamWork-MomsAndBabies#4]
Create Location class with properties:
- [x] Location Code: ex. WASeattle01, WALakewood01 stands for the location of State, City, and store number
- [x] Location Name: WA Seattle 8th Ave 01: ex. State, City, Street, and store number
- [x] Address
- [x] City
- [ ] State
- [x] Zip Code

**Comment by trangtruongus** [comment]
Hi @davischristianson,
I am working on the Location class. There are a couple of things I need your opinions on:
About the State:
- Do you want to use State Abbreviations or Full State Names?
- Do you want users to type in the State or to choose from the dropdown list?
- With the dropdown list, should we use enum for State property?

**Comment by davischristianson** [comment]
Hey @trangtruongus 
The drop down list sounds like a great idea and would be good for the customers. One thing I would do is to make sure there is spaces where they are needed such as New Jersey, West Virginia New York, etc

**Comment by trangtruongus** [comment]
@davischristianson,
Thank you for your insights.
I have updated the Enum. Please take a look and give me some comments.
