### ISSUE TITLE
Create Vendor class

### ISSUE THREAD

**Issue by trangtruongus** [trangtruongus/CPW221-TeamWork-MomsAndBabies#54]
Create Vendor class with properties:
- [x] VendorID (Primary Key/Foreign Key)
- [x] VendorName
- [x] VendorPhone
- [x] VendorEmail
- [x] VendorContactLastName
- [x] VendorContactFirstName

**Comment by davischristianson** [comment]
Check the relationship with this property (VendorID) and the properties of invoices

**Comment by trangtruongus** [comment]
Hi @davischristianson, 
The VendorID is the primary key of the Vendor class, and it is some other classes' FK.
So far, the Vendor class has no FK.
Would you please be more specific on what I should check?
